name: Deploy with OIDC token

on:
  workflow_dispatch:
    inputs:
      apiserver_url:
        description: 'API server URL'
        required: true
        default: 'https://apiserver.example.com'

jobs:
  call-api:
    runs-on: ubuntu-latest
    
    permissions:
      # Necessary for requesting the ID token
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Generate kubeconfig
      run: |
        # Request the OIDC token from GitHub
        export TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                     "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=my-cluster" \
                     | jq -r .value)
        export API_SERVER_URL=${{ github.event.inputs.apiserver_url }}        
        ./gen-kubeconfig.sh        
        cat kubeconfig.yaml
    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        ./deploy.sh